import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Route groups ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-around text-xl h-10 bg-blue-300">
          <p>Home</p>
          <p>About</p>
          <p>Service</p>
        </header>
        {children}
        <footer className="absolute w-full bottom-0 text-center bg-blue-200">
          <p>@ All rights reserved</p>
        </footer>
      </body>
    </html>
  );
}
